# Generated by Django 4.2 on 2026-08-03 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Link this donation to a registered member', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.member'),
        ),
    ]
