# Generated by Django 4.2 on 2026-08-03 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_donation_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('monthly_commitment', models.DecimalField(decimal_places=2, help_text='Amount they agreed to pay each month', max_digits=10)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='donation',
            name='member',
        ),
        migrations.AddField(
            model_name='donation',
            name='monthly_donor',
            field=models.ForeignKey(blank=True, help_text='Link this donation to a registered monthly donor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.monthlydonor'),
        ),
    ]
