# Generated by Django 4.2 on 2026-08-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_monthlydonor_remove_donation_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(default='ANubhavi', max_length=255),
        ),
    ]
