# Generated by Django 4.2 on 2026-08-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_donation_donor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(default='Anubhavi', max_length=255),
        ),
    ]
