# Generated by Django 4.2 on 2026-08-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_donation_donor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(help_text='Type or select a category', max_length=255),
        ),
    ]
