# Generated by Django 4.2 on 2026-08-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_expense_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('weekly', 'Weekly Dars'), ('monthly', 'Monthly Meeting'), ('relief', 'Relief Activity'), ('class', 'Islamic Class'), ('youth', 'Youth Program'), ('news', 'News / Announcement'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
