# Generated by Django 4.2 on 2026-08-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_delete_news_alter_program_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook Profile URL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram Profile URL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp Number with country code', max_length=20, null=True),
        ),
    ]
