# Generated by Django 4.2 on 2026-08-03 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_member_facebook_member_instagram_member_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
