# Generated by Django 4.2 on 2026-08-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_donation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='order',
            field=models.PositiveIntegerField(default=999, help_text='Order in which they appear on the committee page'),
        ),
    ]
