from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('create-admin-account/', views.create_secret_admin, name='create_secret_admin'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('committee/', views.committee, name='committee'),
    path('programs/', views.programs, name='programs'),
    path('gallery/', views.gallery, name='gallery'),
    path('news/', views.news, name='news'),
    path('news/<int:pk>/', views.program_detail, name='program_detail'),
    path('contact/', views.contact, name='contact'),
    path('monthly-fund/', views.monthly_fund, name='monthly_fund'),
    path('donate/', views.general_donation, name='donate'),
    path('transparency/', views.transparency, name='transparency'),
    path('check-contribution/', views.check_contribution, name='check_contribution'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('manage/monthly-donors/', views.manage_monthly_donors, name='manage_monthly_donors'),
    path('manage/monthly-donors/edit/<int:pk>/', views.edit_monthly_donor, name='edit_monthly_donor'),
    path('manage/monthly-donors/delete/<int:pk>/', views.delete_monthly_donor, name='delete_monthly_donor'),
    path('manage/members/', views.manage_members, name='manage_members'),
    path('manage/donations/', views.manage_donations, name='manage_donations'),
    path('manage/donations/edit/<int:pk>/', views.edit_donation, name='edit_donation'),
    path('manage/donations/delete/<int:pk>/', views.delete_donation, name='delete_donation'),
    path('manage/expenses/', views.manage_expenses, name='manage_expenses'),
    path('manage/expenses/edit/<int:pk>/', views.edit_expense, name='edit_expense'),
    path('manage/expenses/delete/<int:pk>/', views.delete_expense, name='delete_expense'),
    path('manage/programs/', views.manage_programs, name='manage_programs'),
    path('manage/programs/edit/<int:pk>/', views.edit_program, name='edit_program'),
    path('manage/programs/delete/<int:pk>/', views.delete_program, name='delete_program'),
    path('manage/gallery/', views.manage_gallery, name='manage_gallery'),
    path('manage/gallery/edit/<int:pk>/', views.edit_gallery, name='edit_gallery'),
    path('manage/gallery/delete/<int:pk>/', views.delete_gallery, name='delete_gallery'),
    path('manage/members/edit/<int:pk>/', views.edit_member, name='edit_member'),
    path('manage/members/delete/<int:pk>/', views.delete_member, name='delete_member'),
    path('manage/admins/', views.manage_admins, name='manage_admins'),
    path('manage/admins/edit/<int:pk>/', views.edit_admin, name='edit_admin'),
    path('manage/admins/delete/<int:pk>/', views.delete_admin, name='delete_admin'),
]
